### PR TITLE
Expose NS attribute of zones

### LINKED ISSUE #29: Expose NS attribute of an Zone
Since the Hetzner nameserver names are very stable, we could provide them as defaults/constants in the provider directly which can be overwritten if needed.

```hcl
locals {
    hetzner_ns1 = "helium.ns.hetzner.de."
    hetzner_ns2 = "hydrogen.ns.hetzner.com."
    hetzner_ns3 = "oxygen.ns.hetzner.com."
}
``` 

Related to https://github.com/timohirt/terraform-provider-hetznerdns/issues/27

### PR DESCRIPTION
**Pull request by jkroepke**
fixes #29

### CODE REVIEW

**Comment by ThomasLandauer** [comment]
How is this working now? Could you add an example to https://registry.terraform.io/providers/germanbrew/hetznerdns/latest/docs/resources/record#example-usage ?
Right now, I'm creating the `hetznerdns_zone` as `resource` (not `data`), and I can't figure out a way to smoothly transition it to what you have in your examples... ;-)

**Comment by kimdre** [comment]
@ThomasLandauer 
`hetznerdns_zone` resource and data source provide a set of the hetznerdns nameserver that are being used (Currently alwas the same three ns).
You can use this set to loop over e.g. a `hetznerdns_record` resource for your `NS` entries like so:

```hcl
# Domain Zone
resource "hetznerdns_zone" "mydomain_de" {
  name = "mydomain.de"
  ttl  = 300
}

# Nameserver entries
resource "hetznerdns_record" "mydomain_de-NS" {
  for_each = toset(hetznerdns_zone.mydomain_de.ns)

  zone_id = hetznerdns_zone.mydomain_de.id
  name    = "@"
  type    = "NS"
  value   = each.value
}
```

**Comment by ThomasLandauer** [comment]
Thanks, I think this worked *partially*: Deleted all my NS records, and recreated them.
However, on a `.ch` domain, I'm getting:
> creating record: error creating record in zone 7UYPkddvJj6isWTSuzHmtT: API returned HTTP 422 Unprocessable Entity error with message: '422 Unprocessable Content: taken: ns1.your-server.de.; '

`.ch` can't be registered normally (like `.de` and `.at`), but only through the old Robot web interface. So it looks like this interferes with the `for_each` here?
One some other (not affected by this) `.ch` domain I'm having 6 NS entries: 3 from the old system (`ns1.your-server.de.` etc.) and the 3 new ones.

**Comment by kimdre** [comment]
I noticed the terraform logic can be a little buggy with this example sometimes.
Because even though terraform should wait until the zone is created with the for_each loop, it sometimes still fails to create the NS records when the zone doesn't exist before the apply.
A ugly workaround is to set the `-paralell` tf argument to `1` but this isn't really a solution. 
I will be adding a new data source to retrieve all nameservers (primary, secondary and konsoleh) with #151 .

**Comment by kimdre** [comment]
@ThomasLandauer The latest release no provides a [nameservers data source](https://registry.terraform.io/providers/germanbrew/hetznerdns/latest/docs/data-sources/nameservers). 
Please open a issue if you encounter any problems.

**Pull request merged**
